title: Marko Čičak # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Date of birth: 22.07.1994
  <br>
  Age: 26
  <br>
  Location: Kaštela / Split / Novska, Croatia
  <br>
  E-mail: markocicak60@gmail.com
  <br>
  Phone: +385994014422
  <br><br>
  <b> Programming Skills: </b>
  <br>
  Unity c#
  <br>
  HTML
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
